openapi: 3.1.0
info:
  title: Financial Manager Auth API
  version: 1.0.0
  description: API for managing authentication (login, signup, and logout)

paths:
  /api/login:
    post:
      tags:
        - Auth Services
      summary: Log into app
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                login:
                  type: string
                  example: "admin"
                password:
                  type: string
                  example: "password"
      responses:
        200:
          description: Login succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "6705d447724aa25c72ff57fc"
                      name:
                        type: string
                        example: "Admin"
                      login:
                        type: string
                        example: "Admin"
                      accountant_balance:
                        type: number
                        example: 0
                  message:
                    type: string
                    example: "OK"
        400:
          description: Bad Request
        401:
          description: Login Invalid

  /api/logout:
    get:
      tags:
        - Auth Services
      summary: End the user session
      responses:
        200:
          description: Successfully logged out
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Successfully logged out"
        400:
          description: Bad Request

  /api/signup:
    post:
      tags:
        - Auth Services
      summary: Create Login
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Admin"
                login:
                  type: string
                  example: "admin"
                password:
                  type: string
                  example: "password"
                passwordRepeat:
                  type: string
                  example: "password"
      responses:
        201:
          description: Login created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "6705d007724aa25c72ff57f8"
                      name:
                        type: string
                        example: "Admin"
                      login:
                        type: string
                        example: "admin"
                      accountant_balance:
                        type: number
                        example: 0
                  message:
                    type: string
                    example: "Your user and default account were created successfully"
        400:
          description: Bad Request
