version: '3.8'

services:
  mongo_financial_manager:
    image: mongo:latest
    ports:
      - "${MONGO_FINANCIAL_MANAGER_PORT}:27017"
    command: mongod --replSet financialDbReplicaSet --bind_ip_all
    networks:
      - mongoCluster
    container_name: mongo_financial_manager
    extra_hosts:
      - host.docker.internal:host-gateway

  mongo_financial_manager_replica_1:
    image: mongo:latest
    ports:
      - "${MONGO_FINANCIAL_MANAGER_REPLICA_1_PORT}:27017"
    command: mongod --replSet financialDbReplicaSet --bind_ip_all
    networks:
      - mongoCluster
    container_name: mongo_financial_manager_replica_1
    extra_hosts:
      - host.docker.internal:host-gateway

  mongo_financial_manager_replica_2:
    image: mongo:latest
    ports:
      - "${MONGO_FINANCIAL_MANAGER_REPLICA_2_PORT}:27017"
    command: mongod --replSet financialDbReplicaSet --bind_ip_all
    networks:
      - mongoCluster
    container_name: mongo_financial_manager_replica_2
    extra_hosts:
      - host.docker.internal:host-gateway

  financial_manager_app:
    build: .
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo_financial_manager
      - mongo_financial_manager_replica_1
      - mongo_financial_manager_replica_2
    networks:
      - mongoCluster
    extra_hosts:
      - host.docker.internal:host-gateway

  init-replica:
    image: mongo:latest
    depends_on:
      - mongo_financial_manager
      - mongo_financial_manager_replica_1
      - mongo_financial_manager_replica_2
    volumes:
      - ./init-replica-set.sh:/init-replica-set.sh
    environment:
      - MONGO_FINANCIAL_MANAGER_PORT=${MONGO_FINANCIAL_MANAGER_PORT}
      - MONGO_FINANCIAL_MANAGER_REPLICA_1_PORT=${MONGO_FINANCIAL_MANAGER_REPLICA_1_PORT}
      - MONGO_FINANCIAL_MANAGER_REPLICA_2_PORT=${MONGO_FINANCIAL_MANAGER_REPLICA_2_PORT}
    entrypoint: ["/bin/bash", "/init-replica-set.sh"]
    networks:
      - mongoCluster
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  node_modules:

networks:
  mongoCluster:
    name: mongoCluster
    driver: bridge